### ISSUE TITLE
Updated to latest version today and the exe is refusting to start.

### ISSUE THREAD

**Issue by RobertSvebeck** [artmamedov/artroom-stable-diffusion#1]
Error message: A javaScript error occured in the main process

... App version is not a valid semver version "0.3.5a" at Object.newError.... (Continues for about 20+ lines).

**Comment by artmamedov** [comment]
Hi yes, sorry was unaware that electron updater didn't accept letter. If it doesn't auto-update to 0.3.6, please install a previous version or you can install 0.3.6 directly. Sorry about that :(

**Comment by RobertSvebeck** [comment]
Reinstalling worked. Thanks for making this software!
