### ISSUE TITLE
longing for a more convenient prompt editor

### ISSUE THREAD

**Issue by mgaillard87** [artmamedov/artroom-stable-diffusion#11]
Rather a request than an issue : horizontal scrolling text field is not convenient to write and modify long, detailed, prompts. Would you consider setting up a multiline text editor with vertical scrolling ?
Once again, thanks for your excellent work

**Comment by artmamedov** [comment]
![image](https://user-images.githubusercontent.com/59179719/189468992-efa45ce7-33b2-49e0-9f45-83e419d15af4.png)

Hi, sure no problem. Adding this in next patch

**Comment by artmamedov** [comment]
I gotchu

**Comment by mgaillard87** [comment]
Excellent !
