### ISSUE TITLE
What is with esrgan resizers in 0.4.0 version?

### ISSUE THREAD

**Issue by mmilekic** [artmamedov/artroom-stable-diffusion#14]
RealESRGAN and ESRGAN dissapered from 0.4.0 ?
I just trying today to resize some photos but realized that this resizer missing?
Can you check?

**Comment by artmamedov** [comment]
Hi! Yes, sorry the real-esrgan was having issues with the new setup (while installing codeformer), so I removed it temporarily. I have some hotfixes to do and then will put it back during this weekend's patch. Sorry for the inconvenience.

**Comment by mmilekic** [comment]
Can you add more setups for realesrgan besides normal and anime? If there are any good AI resizers of whole picture like realesrgan, same or better, can you add these too?
bonus question: SD1.5 and new models? (any idea when?)

**Comment by mmilekic** [comment]
and yes, try to add some changelog details for us, curious ones :)

**Comment by artmamedov** [comment]
New models are on the google drive if you want to check them out https://drive.google.com/drive/folders/117FZ90B5dbrrcrryrJW_NSUVdB6MmhYD?usp=sharing

And I can add in more as they come out. SD1.5 is a ??? but there are loads of custom models coming out. If you find one you like, you can download it and point to it in Settings and it should be set

**Comment by mmilekic** [comment]
SD is Stable Diffusion 1.5 :) ofc :) thanks for new models? These models are latest public available.. No newer anywhere? :) Nice, wiafu is for (nude) anime manga pop culture lovers and standard is official one, as i know...

**Comment by mmilekic** [comment]
hmmm, looks like esrgan resizer still not work, even in latest 0.4.1 version?
while instalation, i get this
==> WARNING: A newer version of conda exists. <==
  current version: 4.14.0
  latest version: 22.9.0

Please update conda by running

    $ conda update -n base -c defaults conda

its ok or not? should i update manualy or just leave as is?

**Comment by artmamedov** [comment]
I haven't seen any core new ones but there's a lot for niche communities that are being developed. Expanding into more models is definitely a direction that we're interested in heading so we'll try and populate them as they come. 

And that's not a big deal, you can leave it as is. RealESRGAN will come in 0.4.2, or do you mean GFPGAN? Is that not working?

**Comment by mmilekic** [comment]
I thought exactly about realesrgan because i use it for resizing.. gfpgan is more like for human faces to recover and improve..
I am not sure about gfpgan, not even tried but readesrgan have problems...

**Comment by artmamedov** [comment]
Hmm maybe you can try codeformer with a strength of 0. Both CodeFormer and GFPGAN use RealESRGAN in the background

**Comment by artmamedov** [comment]
Fixed
