### ISSUE TITLE
Add an unattended mode, to skip pauses in `py_cuda_install.exe`

### ISSUE THREAD

**Issue by brian6932** [artmamedov/artroom-stable-diffusion#15]
So in this `conda.bat` batch script there's a `PAUSE`:
```cmd
Press any key to continue . . .
```
Which breaks unattended installations, an installation argument should be allowed when running the exe to skip/bypass these pauses.
For example something like `/S` in here should work: `Start-Process -Wait ./py_cuda_install.exe -NoNewWindow -ArgumentList /S`.

**Comment by artmamedov** [comment]
Fixed
