### ISSUE TITLE
Fresh install on new machine runs once they encounters scipy error on successive runs

### ISSUE THREAD

**Issue by deramscholzara** [artmamedov/artroom-stable-diffusion#16]
On a fresh windows pro 64bit install (22H2), after installing Artroom, it will work once, but then fail on successive attempts with this error:

ImportError: DLL load failed while importing _fblas: %1 is not a valid Win32 application. ERROR conda.cli.main_run:execute(49): `conda run python optimizedSD/stable_diffusion.py` failed. (See above for error)

Reinstalling Artroom over itself doesn't resolve the issue, but fully uninstalling it and reinstalling allows it to work one time again.

**Comment by deramscholzara** [comment]
I revisited this, and it looks like the issue is that I needed to restart after installation - perhaps the installer could be modified to inform users to do this - or even to have "restart now" or "restart later" buttons?

**Comment by artmamedov** [comment]
Should be fixed I think
