### ISSUE TITLE
conda error

### ISSUE THREAD

**Issue by tateisu** [artmamedov/artroom-stable-diffusion#2]
[artroom-install-failed.txt](https://github.com/artmamedov/artroom-stable-diffusion/files/9479171/artroom-install-failed.txt)

**Comment by tateisu** [comment]
- uninstall Miniconda (before uninstall ArtRoom)
- uninstall ArtRoom
- delete `C:\Users\{username}\.conda`
- install ArtRoom

**Comment by artmamedov** [comment]
It shouldn't affect your current conda environment. I will look into this issue.

**Comment by tateisu** [comment]
It's probably due to my failed attempts to build an Anaconda environment in the past. The .conda folder remained as broken.

**Comment by artmamedov** [comment]
Hi, was this ever resolved with the latest builds?

**Comment by tateisu** [comment]
To reproduce it, I need to recreate the broken `~/.conda`. I can't.
