### ISSUE TITLE
Cuda Out of memory. How do I bypass this?

### ISSUE THREAD

**Issue by NoahMorrisonIT1025** [artmamedov/artroom-stable-diffusion#20]
![image](https://user-images.githubusercontent.com/59972734/204073806-77c48040-0882-43f5-af7a-5c5922670371.png)

**Comment by artmamedov** [comment]
Unfortunately that's a memory error. To remedy this, you need to either reduce the image size, lower the speed, or try a smaller model (2gb model instead of 4gb). Note that 2gb doesn't make it worse, they're rounded and more specialized. Most models are 2gb now.
