### ISSUE TITLE
Black generated pictures

### ISSUE THREAD

**Issue by mpamop** [artmamedov/artroom-stable-diffusion#23]
I trying create pictures, but got black images. Output logs looks normal. I'm tried other samples, speed generations, but continue getting black images. 
Sample:
![seed_2467697196_00001](https://user-images.githubusercontent.com/37378280/206549982-a3011f18-cc33-407c-a7b9-19204f700c00.png)

And program screenshots with logs
![изображение](https://user-images.githubusercontent.com/37378280/206550045-f755a6de-0179-4b3d-8e8b-e49ecb09d847.png)
![изображение](https://user-images.githubusercontent.com/37378280/206550620-c69515d5-bdf2-4555-bc6f-2964a0480a60.png)

**Comment by mpamop** [comment]
Specs: 8 gigs of ram, gtx 1660 super, win 10 21h2

**Comment by SimPiko** [comment]
not sure if it'll help, but in Options there's "Use Full Precision (fix for 1600 cards)". Try enabling it and see if that helps. If not, well, wait for someone more competent than me to fix the thing.

**Comment by artmamedov** [comment]
Hi, that is correct. You need to go to Settings and turn on full precision. However, we put in an auto detection to catch these before they happen. Will need to go back and verify that the auto full precision mode is working. 

In the meantime, please go to Settings and check off full precision. You may need to clear the queue to make sure the old values are all gone.

**Comment by mpamop** [comment]
OK I'll try and send the result later.

**Comment by mpamop** [comment]
ok, with the new version this problem is gone, closing issue
