### ISSUE TITLE
Models from stabilityai not working

### ISSUE THREAD

**Issue by tenzintrepp** [artmamedov/artroom-stable-diffusion#26]
Hi,

Thank you so much for this piece of Software. The UI is just great!

But I have an Issue when I try to load the models Stable Diffusion v2 and 2.1 from stabilityai. Errors below. 
Other models work great.

![sd_error](https://user-images.githubusercontent.com/29088115/211140757-2209454f-33a9-4e2e-9227-52d1fe7a90b0.jpg)

- stabilityai/Stable Diffusion v2 https://huggingface.co/stabilityai/stable-diffusion-2
- stabilityai/Stable Diffusion v2.1 https://huggingface.co/stabilityai/stable-diffusion-2-1

**Comment by artmamedov** [comment]
Hi! Sdv2 will be released in the latest version! We had some big updates and reworks so this patch was a bit delayed. Will hopefully hit beta on Monday and then live shortly after!

**Comment by tenzintrepp** [comment]
Wow, great!
Can't wait to try it out.
