### ISSUE TITLE
Non asCII characters in prompt

### ISSUE THREAD

**Issue by mgaillard87** [artmamedov/artroom-stable-diffusion#5]
Today I got an error when using referent artist name with particular caracters (ü....), in the prompt.  Think It could be solve by forcing to ASCII. This crash is due maybe to the creation of a MsWindows folder with a forbidden character....

**Comment by artmamedov** [comment]
Noted, will work on this issue in next release

**Comment by mgaillard87** [comment]
Many thanks for your excellent work !

**Comment by artmamedov** [comment]
Took a while but finally got it :)

**Comment by artmamedov** [comment]
Fixed as of 0.4.1
