### ISSUE TITLE
Ooooops : no more random

### ISSUE THREAD

**Issue by mgaillard87** [artmamedov/artroom-stable-diffusion#6]
the application does not work when the random box is checked (instant console crash - no error message)

**Comment by artmamedov** [comment]
Hi, fixing this issue in upcoming release

**Comment by mgaillard87** [comment]
Thank you. I am very happy with the upscaler, and the new way to
save/reload parameters is ewsome: think of it as a way to compress an image
file of any size in a tiny text file !
