### ISSUE TITLE
an error occurred on Settings screen (v0.3.8 and v0.3.6)

### ISSUE THREAD

**Issue by fumitakayano** [artmamedov/artroom-stable-diffusion#8]
an error occurred on Settings scree()

Error message title is 'A JavaScript error occured in the main process'
and 
sub messages are
---
Uncaught Exception:
Error: C:\Users\XXXXXXXXX\artroom miniconda3 envs\artroom-Idm\python.exe: can't open file 'updateConfig.py': [Errno 2] No such file or directory

  at PythonShell.parseError (C:\Program 
Files\Artroom resources¥app.asar\node_modules\python-shell\index.js:303:21)
  at terminatelfNeeded (C:\Program 
Files\Artroom\resources\app.asar\node_modules\python-shell¥index.js:190:32)
  at ChildProcess.<anonymous> (C:\Program
Files\Artroom\resources\app.asar\node_modules\python-shell\index.js:182:13)
  at ChildProcess.emit (events.js:315:20)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
---
that was the report.

**Comment by artmamedov** [comment]
Hi, fixing this issue in upcoming release

**Comment by fumitakayano** [comment]
thank you so much.
