### ISSUE TITLE
possibility to loop

### ISSUE THREAD

**Issue by rothzeta** [artmamedov/artroom-stable-diffusion#9]
When generating 100 images it tries to alocate the memory for all of them at once rtesulting in a crash, maybe you can add a repeat param to do it batches instead.

Thanks

**Comment by artmamedov** [comment]
Hi,
Yes this will be the next big feature release. It'll be a bigger queue system and will also let you vary the prompt out of those 100. Have some more quality of life and performance things to address and then will work on that

**Comment by rothzeta** [comment]
Great news. I'll be eagerly waiting

Keep  up  the excelent work :)
